REVOKE ALL PRIVILEGES ON *.* FROM 'INNOVATION'@'%';
DROP USER IF EXISTS 'INNOVATION'@'%';

DROP DATABASE IF EXISTS INNOVATION;

CREATE USER IF NOT EXISTS 'INNOVATION'@'%' IDENTIFIED BY 'wqs99999';

CREATE DATABASE IF NOT EXISTS INNOVATION CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON INNOVATION.* TO 'INNOVATION'@'%';

USE INNOVATION;

DROP TABLE IF EXISTS item;

CREATE TABLE item (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40),
    userId VARCHAR(30)
);

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    id VARCHAR(30) PRIMARY KEY,
    name VARCHAR(20),
    phone VARCHAR(13),
    accessLevel TINYINT
);
